// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpIlvJT-GNWfIcLToTbl1cmyAfLrL2t6w',
    appId: '1:826156598806:web:f4fc7c0acb9ad9ec921737',
    messagingSenderId: '826156598806',
    projectId: 'learning-env-66ece',
    authDomain: 'learning-env-66ece.firebaseapp.com',
    storageBucket: 'learning-env-66ece.appspot.com',
    measurementId: 'G-9DF2BM4DPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEgIpL9llUdJJXranA243v7-qI2FjgbE',
    appId: '1:826156598806:android:328ddafa7cbfa384921737',
    messagingSenderId: '826156598806',
    projectId: 'learning-env-66ece',
    storageBucket: 'learning-env-66ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRQfWdhsmBjhy-5Ovz81eFaiMuuGAHfWE',
    appId: '1:826156598806:ios:c4a7c38dfa2cea26921737',
    messagingSenderId: '826156598806',
    projectId: 'learning-env-66ece',
    storageBucket: 'learning-env-66ece.appspot.com',
    iosClientId: '826156598806-hh2dced4vnl409mi7lna6cb26qcd9ss4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRQfWdhsmBjhy-5Ovz81eFaiMuuGAHfWE',
    appId: '1:826156598806:ios:c4a7c38dfa2cea26921737',
    messagingSenderId: '826156598806',
    projectId: 'learning-env-66ece',
    storageBucket: 'learning-env-66ece.appspot.com',
    iosClientId: '826156598806-hh2dced4vnl409mi7lna6cb26qcd9ss4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppFirebase',
  );
}
